# Generated by Django 5.0.7 on 2024-07-15 05:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_image_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/product/'),
            preserve_default=False,
        ),
    ]
