# Generated by Django 5.0.7 on 2024-07-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warning',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
