# Generated by Django 5.0.7 on 2024-07-18 00:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_description_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/category/'),
            preserve_default=False,
        ),
    ]
